defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  eb7859f1-a74d-4a53-9e88-225a9c6a49bc: # landing-page-craft
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
